name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Check package.json
        run: |
          # Ensure version hasn't been changed in PR
          git fetch origin master
          MASTER_VERSION=$(git show origin/master:package.json | jq -r .version)
          PR_VERSION=$(jq -r .version package.json)
          if [ "$MASTER_VERSION" != "$PR_VERSION" ]; then
            echo "::warning::Version changed in PR. This should be done during release."
          fi
      
      - name: Validate commits
        uses: webiny/action-conventional-commits@v1.1.0
      
      - name: Check for large files
        run: |
          find . -type f -size +1M | grep -v node_modules | grep -v .git > large_files.txt || true
          if [ -s large_files.txt ]; then
            echo "::warning::Large files detected:"
            cat large_files.txt
          fi
      
      - name: Label PR
        uses: actions/labeler@v4
        if: github.event_name == 'pull_request'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  size-check:
    name: Package Size Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Check package size
        run: |
          npm pack --dry-run 2>&1 | grep "npm notice" > size_output.txt || true
          SIZE=$(cat size_output.txt | grep -oE "[0-9.]+ [kKmMgG]B" | tail -1 || echo "unknown")
          echo "Package size: $SIZE"
          echo "::notice::Package size is $SIZE"